### ISSUE TITLE
Require to free() the dataset Ptr

### ISSUE THREAD

**Issue by WillfordZhan** [JesseZheng/PO_Project2#1]
No free() after malloc(), the `dataset` ptr should be freed in the end of the main function

**Comment by JesseZheng** [comment]
I have added free() at the end of the main fucntion, thanks for your reminder.

**Comment by JesseZheng** [comment]
> No free() after malloc(), the `dataset` ptr should be freed in the end of the main function

I have added free() at the end of the main fucntion, thanks for your reminder.
